### ISSUE TITLE
"Connected as" for main account.

### ISSUE THREAD

**Issue by fokshadev** [Melonai/rust-nitro-sniper#1]
It only shows "Connected as" for sub accounts, It would be really awesome if it showed for the main account too, so It doesn't confuse us

**Comment by fokshadev** [comment]
![image](https://user-images.githubusercontent.com/55259471/89543773-a0a5aa80-d801-11ea-9a2a-c4e4abcc1149.png)
Stuck on this if you put main token, and sub token the same

**Comment by melnary** [comment]
Both problems were addressed in ffbc7add607abff0b2069e2fea5ae2dce75dfd53 (RNA 2.1.0). Thanks for the issue!
