### ISSUE TITLE
I have a Question

### ISSUE THREAD

**Issue by PeterStrick** [Melonai/rust-nitro-sniper#11]
Hello! I recently worked on a project called [NitroSniperGUI](https://github.com/PeterStrick/NitroSniperGUI) which allows you to easily run, manage, update, use and configure the Nitro Sniper.

Currently I include your Nitro Sniper and the following Nitro Snipers, as well as credited you and linked your Nitro Sniper:
https://github.com/Vedzaa/NitroSniper
https://github.com/Vedzaa/NitroSniperGo

So, I am here to ask if it is ok with you, for me to bundle your Nitro Sniper, or if you want me to stop bundling your Nitro Sniper.

Thanks!

Peter Strick

**Comment by fokshadev** [comment]
Hello! We've noticed your project and it's really cool. Good luck with the project!

And sure, we are fine with you bundling the Rust Nitro Sniper in your project.

**Comment by PeterStrick** [comment]
Thanks!
