### ISSUE TITLE
Linux memory leak

### ISSUE THREAD

**Issue by D3XX3R** [Melonai/rust-nitro-sniper#13]
I've been trying it for two days now and I get a big memory leak with the precompiled linux file.
Memory usage was going up from ~50 MB to ~1.3 GB

**Comment by melnary** [comment]
On it!

**Comment by melnary** [comment]
RNS used an older version of the Serenity 0.9.0 release candidate, which supposedly had a memory leak somewhere. It looks like they managed to patch it and if this was the issue, it's fixed in RNS 2.6.6!
I'll close this for now, but if the leak still persists please open this issue again. ^^
