### ISSUE TITLE
Nitro Code

### ISSUE THREAD

**Issue by 0xm00n** [Melonai/rust-nitro-sniper#14]
![Screen Shot 2020-11-11 at 7 21 35 AM](https://user-images.githubusercontent.com/71098497/98811251-8aa21a00-23ee-11eb-837d-ddfe022221e2.png)

Does this tool automatically redeem nitro for me? or do i have to manually do it?

**Comment by melnary** [comment]
Wouldn't be much of a sniper if it didn't! ^^

**Comment by 0xm00n** [comment]
lol thx. something i noticed is that this tool is a little slow. every code seems to be getting redeemed by other snipers.

**Comment by melnary** [comment]
Trust me when I say this, the tool itself is not slow. The latency between it receiving the code and starting a redeem request is just a few nanoseconds. The real main bottleneck is the connection to Discord itself, so basically you're better off if you're closer to the servers! I can guarantee you thought that even with that bit of latency it's possible to snipe codes though, but you need better servers and a bit of luck.

**Comment by 0xm00n** [comment]
hmm. ok ill keep trying this sniper. ill let you know if theres any updates on the latency.
