### ISSUE TITLE
How to use this tool on linux?

### ISSUE THREAD

**Issue by TnkrrGit** [Melonai/rust-nitro-sniper#15]
How do i run this tool on ubuntu 18.04 server linux?

**Comment by melnary** [comment]
First get a binary by either building RNS yourself or by downloading the pre-built Linux binary in the releases section, then simply execute it!

**Comment by TnkrrGit** [comment]
Whats the command to execute it?

**Comment by melnary** [comment]
`./rust-nitro-sniper` 
;3

**Comment by TnkrrGit** [comment]
How do you keep running in background?

**Comment by melnary** [comment]
Just add an `&` at the end of the command like this:
`./rust-nitro-sniper &`
It'll keep posting messages and stop when the shell it's started from is closed.
If you want to keep it running in the background until the server restarts use `disown` after running the previous command.

Please try to google these questions yourself, as these are just basic Linux commands. ^^'
I'll be glad to answer some questions more specific to the sniper itself though!
