### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Jesper-N** [Melonai/rust-nitro-sniper#17]
Hello not an issue, just wanted to ask how you compile it into a linux and windows file from the source code? I'm using a  windows pc.

**Comment by melnary** [comment]
To compile to Linux from Windows you'd need to install the C Linux libraries first. I really wouldn't recommend you to do that.
Instead, use [cross](https://github.com/rust-embedded/cross). It uses Docker to create the proper build environment of the respective platform as a container by itself. I actually already use cross to compile RNS through TravisCI.
As for compiling for Windows, that should work out of the box! ^^
