### ISSUE TITLE
Deploy to heroku button

### ISSUE THREAD

**Issue by is-ege** [Melonai/rust-nitro-sniper#20]
As the title suggests, a deploy to heroku button. Heroku servers usually get low latency in other snipers. I am a brainlet so i dont know how i can deploy it myself. please add

**Comment by melnary** [comment]
Sure sounds good! I'll add it later.

**Comment by fokshadev** [comment]
soon...

**Comment by PoloNX** [comment]
> soon...

Waiting for 2 years now ( ͡° ͜ʖ ͡°)
