### ISSUE TITLE
Doesn't capture

### ISSUE THREAD

**Issue by Jev1337** [Melonai/rust-nitro-sniper#4]
I sent fake gift and It doesn't read them :v

**Comment by Jev1337** [comment]
Also for some reasons it says I made the wrong format when I put sub tokens

**Comment by melnary** [comment]
Hi! Thanks for opening an issue!
First, have you made sure that your fake gift won't be ignored by RNS? Please note that it only checks for gifts that are exactly 16 characters long, as that is the format Discord has picked for them.
For the config, could you please post yours here (with the tokens obviously removed), so I can see what went wrong?

**Comment by Jev1337** [comment]
Sure! Thanks for the quick reply! Didn't expect it!
Thanks it works I tried it now It only detects 16 Ch Long ones.
BTW! There are longer than 16~! I guess? I don't know, I have been using a sniper, private one and they go up to 26!

Also for the config one minute!

**Comment by Jev1337** [comment]
![image](https://user-images.githubusercontent.com/19759761/90280434-d29eb880-de62-11ea-8cfc-855947d49fe8.png)

**Comment by Jev1337** [comment]
![image](https://user-images.githubusercontent.com/19759761/90280449-daf6f380-de62-11ea-9cb4-dde6de3a237f.png)

**Comment by Jev1337** [comment]
Config Fixed! I was missing "" my bad! Sorry!

**Comment by Jev1337** [comment]
I have a question tho, How did you built it in a way it's only 8mb? What did you use to build it?

**Comment by melnary** [comment]
While we were researching codes we couldn't find a single one that wasn't 16 chars. Although it could be the case that there are some, you never know with these things! If you ever find one that isn't 16 chars and that Discord actually recognizes, please send it to me, in that case I'll change the detection as soon as possible ^^'
Although I could also introduce a config setting that controls whether RNS checks for longer/shorter codes, If you'd think such a feature would be useful!

**Comment by noto-rious** [comment]
The ones longer than 16 are for games/apps and not Nitro. Nitro codes will only be 16 characters long. Hopefully this clears up any confusion you two are having.

**Comment by Jev1337** [comment]
> The ones longer than 16 are for games/apps and not Nitro. Nitro codes will only be 16 characters long. Hopefully this clears up any confusion you two are having.

Yes! That's what I was going to say! I will end this here. I'm going to create a new issue suggesting something!
