### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jev1337** [Melonai/rust-nitro-sniper#5]
Hi! I came back again to suggest something.
Is it possible to make the program work with Webhook to make Embed messages to notify the user that the sniper sniped Nitro on X channel by X user

Such as this one
![image](https://user-images.githubusercontent.com/19759761/90313631-f8c96480-df05-11ea-86f1-f2b0f51b3e39.png)

**Comment by melnary** [comment]
Sure! I'll get right on it!

**Comment by Jev1337** [comment]
I will provide as much information as I can!

I can tell you that that program requires Webhook link (from the server channel you want to get notified on) on a text file next to the exe location (just like rna_config). But I assume you can throw that in the same file!

Thanks for taking my suggestion in!

**Comment by melnary** [comment]
Added in commit fa24d1cabe51ea466f75e42a035ef5f604167fcc (RNS 2.2.0). The builds will be up soon!

**Comment by melnary** [comment]
...and this is how the messages end up looking! ^^

<img width="414" alt="Screenshot 2020-08-15 at 23 04 24" src="https://user-images.githubusercontent.com/10659529/90321619-ad39a980-df4b-11ea-99c4-e549982b1d7c.png">
