### ISSUE TITLE
Small Bug

### ISSUE THREAD

**Issue by Jev1337** [Melonai/rust-nitro-sniper#6]
Tag is #0600 not #600
It doesn't read the first zeros, same with my alt, It's #0017 but reads it as #17
![image](https://user-images.githubusercontent.com/19759761/90322668-d576d780-df4e-11ea-88b4-c2ac33ecad03.png)

**Comment by melnary** [comment]
Ahh I knew I forgot that somewhere! Luckily it's an easy enough fix.

**Comment by melnary** [comment]
Addressed in c006b6118b4d56c29aeb06f808c03bd9981ded1c (RNS 2.2.1).
