### ISSUE TITLE
New Discord API

### ISSUE THREAD

**Issue by Jev1337** [Melonai/rust-nitro-sniper#7]
Just FYI, I don't know if this will affect RNS or not ^^

**Comment by melnary** [comment]
The latest version of the API I see is v8, we're on v6 as for now. Technically there shouldn't be any real harm of being on an older version as long as it's supported. I'll check if there's a difference in speed though!

**Comment by fokshadev** [comment]
We checked for the speed difference, and it's exactly the same; We are sticking to v6 as long as it's supported, as mentioned above ^.
