### ISSUE TITLE
Suggestion #2

### ISSUE THREAD

**Issue by Jev1337** [Melonai/rust-nitro-sniper#8]
1- duplicate code detector to avoid being throttled.
(for example 2 codes sent exactly at the same time and sends only 1 HTTP request).
2- Giveaway joined (tbh I don't like this)
3- Garbage collector (a temporary 12 Hour garbage meaning it will block codes that are in the garbage for less spam)
4- Server Block (A server list using ServerID to block certain servers)

**Comment by melnary** [comment]
Duplicate code protection is definitely something I'll need to add!
I feel like joining giveaways is somewhat out of scope for RNS, but it could be a feature in the future.
I'm guessing 3 is pretty much the same as 1, although blocking the codes for as long as RNS is running is a more simpler approach than tracking time.
I'm not quite sure about the server block though, what would you get out of that?

**Comment by Jev1337** [comment]
4 is for example I wanna do a gift giveaway everyday for example on myserver, i'd whitelist it ^^

**Comment by melnary** [comment]
Implemented in RNS 2.4.1.
